export const TOGGLE_ISNAV = 'TOGGLE_ISNAV';
export const CLOSE_ISNAV = 'CLOSE_ISNAV';
export const REPLACE_PROJECTS = 'REPLACE_PROJECTS';
export const REPLACE_CATEGORIES = 'REPLACE_CATEGORIES';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
